/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OidcCallbackImport } from './routes/oidc-callback'
import { Route as ErrorImport } from './routes/error'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedDashboardProjectsIndexImport } from './routes/_authenticated/_dashboard/projects/index'
import { Route as AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdIndexImport } from './routes/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/index'
import { Route as AuthenticatedDashboardAmendmentsProjectProjectIdDocumentDocumentIdIndexImport } from './routes/_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/index'
import { Route as AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdConditionConditionNumberIndexImport } from './routes/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/index'

// Create/Update Routes

const OidcCallbackRoute = OidcCallbackImport.update({
  path: '/oidc-callback',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardProjectsIndexRoute =
  AuthenticatedDashboardProjectsIndexImport.update({
    path: '/projects/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdIndexRoute =
  AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdIndexImport.update(
    {
      path: '/conditions/project/$projectId/document/$documentId/',
      getParentRoute: () => AuthenticatedDashboardRoute,
    } as any,
  )

const AuthenticatedDashboardAmendmentsProjectProjectIdDocumentDocumentIdIndexRoute =
  AuthenticatedDashboardAmendmentsProjectProjectIdDocumentDocumentIdIndexImport.update(
    {
      path: '/amendments/project/$projectId/document/$documentId/',
      getParentRoute: () => AuthenticatedDashboardRoute,
    } as any,
  )

const AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdConditionConditionNumberIndexRoute =
  AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdConditionConditionNumberIndexImport.update(
    {
      path: '/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/',
      getParentRoute: () => AuthenticatedDashboardRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_dashboard/projects/': {
      id: '/_authenticated/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIndexImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/': {
      id: '/_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/'
      path: '/amendments/project/$projectId/document/$documentId'
      fullPath: '/amendments/project/$projectId/document/$documentId'
      preLoaderRoute: typeof AuthenticatedDashboardAmendmentsProjectProjectIdDocumentDocumentIdIndexImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/': {
      id: '/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/'
      path: '/conditions/project/$projectId/document/$documentId'
      fullPath: '/conditions/project/$projectId/document/$documentId'
      preLoaderRoute: typeof AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdIndexImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
    '/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/': {
      id: '/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/'
      path: '/conditions/project/$projectId/document/$documentId/condition/$conditionNumber'
      fullPath: '/conditions/project/$projectId/document/$documentId/condition/$conditionNumber'
      preLoaderRoute: typeof AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdConditionConditionNumberIndexImport
      parentRoute: typeof AuthenticatedDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedDashboardRoute: AuthenticatedDashboardRoute.addChildren({
      AuthenticatedDashboardProjectsIndexRoute,
      AuthenticatedDashboardAmendmentsProjectProjectIdDocumentDocumentIdIndexRoute,
      AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdIndexRoute,
      AuthenticatedDashboardConditionsProjectProjectIdDocumentDocumentIdConditionConditionNumberIndexRoute,
    }),
  }),
  ErrorRoute,
  OidcCallbackRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/error",
        "/oidc-callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_dashboard"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/oidc-callback": {
      "filePath": "oidc-callback.tsx"
    },
    "/_authenticated/_dashboard": {
      "filePath": "_authenticated/_dashboard.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_dashboard/projects/",
        "/_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/",
        "/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/",
        "/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/"
      ]
    },
    "/_authenticated/_dashboard/projects/": {
      "filePath": "_authenticated/_dashboard/projects/index.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/": {
      "filePath": "_authenticated/_dashboard/amendments/project/$projectId/document/$documentId/index.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/": {
      "filePath": "_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/index.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/": {
      "filePath": "_authenticated/_dashboard/conditions/project/$projectId/document/$documentId/condition/$conditionNumber/index.tsx",
      "parent": "/_authenticated/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
