"""Added table for amendment

Revision ID: 1041c57bc31f
Revises: 1bb20510b916
Create Date: 2024-10-23 16:05:02.551353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1041c57bc31f'
down_revision = '1bb20510b916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subconditions', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'), schema='condition')
    op.create_table('amendments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('amended_document_id', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('amendment_name', sa.Text(), nullable=True),
    sa.Column('date_issued', sa.Date(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['condition.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amended_document_id', name='uq_amended_document'),
    schema='condition'
    )
    op.add_column(
        'conditions',
        sa.Column('amended_document_id', sa.String(), nullable=True),
        schema='condition'
    )
    op.create_foreign_key(
        'fk_conditions_amended_document_id',
        'conditions',
        'amendments',
        ['amended_document_id'],
        ['amended_document_id'],
        source_schema='condition',
        referent_schema='condition',
        ondelete='CASCADE'
    )
    op.alter_column(
        'conditions', 
        'is_active',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text('true'),
        schema='condition'
    )
    op.add_column('subconditions', sa.Column('amended_document_id', sa.String(), nullable=True), schema='condition')
    op.create_foreign_key(
        'fk_subconditions_amended_document_id',
        'subconditions',
        'amendments',
        ['amended_document_id'],
        ['amended_document_id'],
        source_schema='condition',
        referent_schema='condition',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conditions_amended_document_id', 'conditions', type_='foreignkey', schema='condition')
    op.drop_column('conditions', 'amended_document_id', schema='condition')
    op.alter_column(
        'conditions', 
        'is_active',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),
        schema='condition'
    )
    op.drop_constraint('fk_subconditions_amended_document_id', 'subconditions', type_='foreignkey', schema='condition')
    op.drop_column('subconditions', 'amended_document_id', schema='condition')
    op.drop_column('subconditions', 'is_active', schema='condition')
    op.drop_table('amendments', schema='condition')
    # ### end Alembic commands ###
