"""add_subcondition_table

Revision ID: 116b6b166311
Revises: 2f7ba59267b1
Create Date: 2024-09-11 15:39:05.376627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116b6b166311'
down_revision = '2f7ba59267b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliverables', 'fn_consultation_required', new_column_name='consultation_required', schema='condition')
    op.add_column('conditions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), schema='condition')
    op.create_table('subconditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('subcondition_identifier', sa.String(), nullable=True),
    sa.Column('subcondition_text', sa.Text(), nullable=True),
    sa.Column('parent_subcondition_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_subcondition_id'], ['condition.subconditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='condition'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subconditions', schema='condition')
    op.alter_column('condition.deliverables', 'consultation_required', new_column_name='fn_consultation_required')
    op.drop_column('condition.conditions', 'is_active')
    # ### end Alembic commands ###
