"""Added new column to Project

Revision ID: 1bb20510b916
Revises: 919c83d6206d
Create Date: 2024-10-17 17:05:09.083820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb20510b916'
down_revision = '919c83d6206d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.Text(), nullable=True), schema='condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type', schema='condition')
    # ### end Alembic commands ###
