"""create_initial_tables

Revision ID: 2f7ba59267b1
Revises: 
Create Date: 2024-09-06 15:54:47.236956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7ba59267b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('document_file_name', sa.Text(), nullable=True),
    sa.Column('date_issued', sa.Date(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('first_nations', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('consultation_records_required', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_id', name='uq_project_document'),
    schema='condition'
    )
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('condition_name', sa.Text(), nullable=True),
    sa.Column('condition_number', sa.Integer(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('topic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('subtopic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('deliverable_name', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'document_id'], ['condition.projects.project_id', 'condition.projects.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='condition'
    )
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_name', sa.Text(), nullable=True),
    sa.Column('is_plan', sa.Boolean(), nullable=True),
    sa.Column('approval_type', sa.Text(), nullable=True),
    sa.Column('stakeholders_to_consult', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('stakeholders_to_submit_to', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('fn_consultation_required', sa.Boolean(), nullable=True),
    sa.Column('related_phase', sa.Text(), nullable=True),
    sa.Column('days_prior_to_commencement', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='condition'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliverables', schema='condition')
    op.drop_table('conditions', schema='condition')
    op.drop_table('projects', schema='condition')
    # ### end Alembic commands ###
