"""update_text_in_attribute_keys

Revision ID: 42d3651e98e4
Revises: 803abfe08b15
Create Date: 2025-05-13 12:40:29.172856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d3651e98e4'
down_revision = '803abfe08b15'
branch_labels = None
depends_on = None


UPDATES = [
    ('Requires management plan', 'Requires management plan(s)'),
    ('Management plan name', 'Management plan name(s)'),
    ('Management plan acronym', 'Management plan acronym(s)'),
    ('Milestone(s) related to plan implementation', 'Project phases(s) related to plan implementation'),
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for old, new in UPDATES:
        op.execute(
            f"""
            UPDATE condition.attribute_keys
            SET key_name = '{new}'
            WHERE key_name = '{old}';
            """
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for old, new in UPDATES:
        op.execute(
            f"""
            UPDATE condition.attribute_keys
            SET key_name = '{old}'
            WHERE key_name = '{new}';
            """
        )
    # ### end Alembic commands ###
