"""update_condition_attribute_table_structure

Revision ID: 5b00cd6b3172
Revises: dfbd78ccb7bd
Create Date: 2024-11-20 15:50:34.508239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b00cd6b3172'
down_revision = 'dfbd78ccb7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conditions',
        sa.Column('is_condition_attributes_approved', sa.Boolean(), nullable=True),
        schema='condition'
    )
    op.create_table('condition_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('attribute_key', sa.Text(), nullable=False),
    sa.Column('attribute_value', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='condition'
    )
    op.drop_table('condition_requirements', schema='condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'is_condition_attributes_approved', schema='condition')
    op.drop_table('condition_attributes', schema='condition')
    op.create_table('condition_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('deliverable_name', sa.Text(), nullable=True),
    sa.Column('is_plan', sa.Boolean(), nullable=True),
    sa.Column('approval_type', sa.Text(), nullable=True),
    sa.Column('stakeholders_to_consult', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('stakeholders_to_submit_to', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('consultation_required', sa.Boolean(), nullable=True),
    sa.Column('related_phase', sa.Text(), nullable=True),
    sa.Column('days_prior_to_commencement', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='condition'
    )
    # ### end Alembic commands ###
