"""add_deliverable_name

Revision ID: 6c06ecce254a
Revises: 42d3651e98e4
Create Date: 2025-05-20 15:36:33.674287

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '6c06ecce254a'
down_revision = '42d3651e98e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    attribute_keys = sa.table('attribute_keys',
                              sa.column('id', sa.Integer),
                              sa.column('key_name', sa.String),
                              sa.column('created_date', sa.DateTime),
                              sa.column('external_key', sa.String),
                              sa.column('sort_order', sa.Integer),
                              schema='condition')

    # Use op.bulk_insert with the table object
    op.bulk_insert(attribute_keys, [
        {'id': 12, 'key_name': 'Deliverable name', 'created_date': datetime.utcnow(),
         'external_key': 'deliverable_name', 'sort_order': 12}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM condition.attribute_keys
        WHERE id = 12 AND key_name = 'Deliverable name' AND external_key = 'deliverable_name';
        """
    )
    # ### end Alembic commands ###
