"""update_key_in_attribute_keys

Revision ID: 803abfe08b15
Revises: 2ab69892d3a5
Create Date: 2025-04-21 11:50:15.462923

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '803abfe08b15'
down_revision = '2ab69892d3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE condition.attribute_keys
        SET key_name = 'Milestone(s) related to plan submission'
        WHERE key_name = 'Milestone related to plan submission';
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE condition.attribute_keys
        SET key_name = 'Milestone related to plan submission'
        WHERE key_name = 'Milestone(s) related to plan submission';
    """)
    # ### end Alembic commands ###
