"""remove_requires_management_plan_key

Revision ID: af25a1d94134
Revises: c7cbe44e54fc
Create Date: 2025-07-03 09:17:25.522029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af25a1d94134'
down_revision = 'c7cbe44e54fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM condition.attribute_keys
        WHERE key_name = 'Requires management plan(s)';
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO condition.attribute_keys (key_name, external_key, sort_order)
        VALUES ('Requires management plan(s)', 'requires_management_plan', 1);
        """
    )
    # ### end Alembic commands ###
