"""remove_cascade_from_project

Revision ID: d909569f8c4e
Revises: af25a1d94134
Create Date: 2025-08-11 14:39:30.881474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd909569f8c4e'
down_revision = 'af25a1d94134'
branch_labels = None
depends_on = None

OLD_FK_NAME = 'documents_project_id_fkey'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing FK constraint
    op.drop_constraint(OLD_FK_NAME, 'documents', schema='condition', type_='foreignkey')

    # Recreate FK with RESTRICT (or just omit ondelete to default to restrict)
    op.create_foreign_key(
        OLD_FK_NAME,
        'documents', 'projects',
        ['project_id'], ['project_id'],
        source_schema='condition',
        referent_schema='condition',
        ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(OLD_FK_NAME, 'documents', schema='condition', type_='foreignkey')

    op.create_foreign_key(
        OLD_FK_NAME,
        'documents', 'projects',
        ['project_id'], ['project_id'],
        source_schema='condition',
        referent_schema='condition',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
