"""add_standard_condition_flag

Revision ID: e4912bf17735
Revises: ac00a91a43c4
Create Date: 2025-01-09 11:33:34.102623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4912bf17735'
down_revision = 'ac00a91a43c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attribute_keys", schema='condition') as batch_op:
        batch_op.add_column(sa.Column('external_key', sa.Text(), nullable=True))

    attribute_key = sa.table('attribute_keys',
                             sa.Column('key_name', sa.Text()),
                             sa.Column('external_key', sa.Text()),
                             schema='condition')

    updates = {
        "Requires consultation": "requires_consultation",
        "Parties required to be submitted": "parties_required_to_be_submitted",
        "Parties required to be consulted": "parties_required_to_be_consulted",
        "Management plan name": "management_plan_name",
        "Requires management plan": "requires_management_plan",
        "Submitted to EAO for": "submitted_to_eao_for",
        "Milestone related to plan submission": "milestone_related_to_plan_submission",
        "Milestone(s) related to plan implementation": "milestones_related_to_plan_implementation",
        "Time associated with submission milestone": "time_associated_with_submission_milestone",
        "Management Plan Acronym": "management_plan_acronym",
    }

    for key_name, external_key in updates.items():
        op.execute(
            attribute_key.update()
            .where(attribute_key.c.key_name == key_name)
            .values(external_key=external_key)
        )

    with op.batch_alter_table("conditions", schema='condition') as batch_op:
        batch_op.add_column(sa.Column('is_standard_condition', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attribute_keys", schema='condition') as batch_op:
        batch_op.drop_column("external_key")

    with op.batch_alter_table("conditions", schema='condition') as batch_op:
        batch_op.drop_column("is_standard_condition")
    # ### end Alembic commands ###
