apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
{{ include "condition-cron.labels" . | indent 4 }}
data:
  crontab: |-
{{ .Values.cronTab | indent 4 }}
  FLASK_ENV: "{{ .Values.flask.env }}"
  DATABASE_HOST: "{{ .Values.database.host }}"
  DATABASE_PORT: "{{ .Values.database.port }}"
  S3_BUCKET: "{{ .Values.s3.bucket }}"
  S3_HOST: "{{ .Values.s3.host }}"
  S3_REGION: "{{ .Values.s3.region }}"
  S3_SERVICE: "{{ .Values.s3.service }}"
  EXTRACTOR_API_URL: "{{ .Values.extractor.apiUrl }}"
