apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "condition-cron.labels" . | indent 4 }}
type: Opaque
data:
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | b64enc | quote }}
  EXTRACTOR_API_KEY: {{ .Values.secrets.extractorApiKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
