apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      initContainers:
        - name: pre-hook-update-db
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /opt/app-root/pre-hook-update-db.sh
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret }}
                  key: app-db-username
            - name: DATABASE_HOST
              value: {{ .Values.database.service.name }}
            - name: DATABASE_PORT
              value: "{{ .Values.database.service.port }}"
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ tpl .Values.image.repository . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.cpu.limit }}
              memory: {{ .Values.resources.memory.limit }}
            requests:
              cpu: {{ .Values.resources.cpu.request }}
              memory: {{ .Values.resources.memory.request }}
          readinessProbe:
            httpGet:
              path: /ops/readyz
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ops/healthz
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret }}
                  key: app-db-name
            - name: DATABASE_HOST
              value: {{ .Values.database.service.name }}
            - name: DATABASE_PORT
              value: "{{ .Values.database.service.port }}"
            - name: JWT_OIDC_ALGORITHMS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_ALGORITHMS
            - name: JWT_OIDC_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_AUDIENCE
            - name: JWT_OIDC_CACHING_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_CACHING_ENABLED
            - name: JWT_OIDC_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_ISSUER
            - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_JWKS_CACHE_TIMEOUT
            - name: JWT_OIDC_WELL_KNOWN_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: JWT_OIDC_WELL_KNOWN_CONFIG
            - name: PYTHONBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: PYTHONBUFFERED
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: KEYCLOAK_REALM_NAME
            - name: KEYCLOAK_ADMIN_CLIENT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: KEYCLOAK_ADMIN_CLIENT
            - name: KEYCLOAK_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: KEYCLOAK_ADMIN_SECRET
            - name: CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: CONNECT_TIMEOUT
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: CORS_ORIGIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
