apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "VITE_ENV": "{{ .Values.app.env }}",
        "VITE_API_URL": "{{ .Values.app.api }}",
        "VITE_VERSION": "{{ .Values.app.version }}",
        "VITE_APP_TITLE": "{{ .Values.app.title }}",
        "VITE_APP_URL": "{{ .Values.app.url }}",
        "VITE_OIDC_AUTHORITY": "{{ .Values.app.oidcAuthority }}",
        "VITE_CLIENT_ID": "{{ .Values.app.clientId }}",
        "SUPPORT_EMAIL": "{{ .Values.app.supportEmail }}",
      }